"""add_image

Revision ID: 1d27fd882600
Revises: cc396ecd8cd9
Create Date: 2026-05-20 00:40:03.726023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from application.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '1d27fd882600'
down_revision: Union[str, Sequence[str], None] = 'cc396ecd8cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.add_column(
        'blog_post',
        sa.Column(
            'image_path',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=True,
        ),
        schema='application',
    )
    op.drop_column('blog_post', 'image', schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'blog_post',
        sa.Column(
            'image', sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        schema='application',
    )
    op.drop_column('blog_post', 'image_path', schema='application')
    op.create_table(
        'alembic_version',
        sa.Column(
            'version_num',
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            'version_num', name=op.f('alembic_version_pkc')
        ),
    )
    # ### end Alembic commands ###
