"""add_unique_constraint_to_location_name

Revision ID: 869df2353e62
Revises: 48c7effbe24b
Create Date: 2026-04-04 15:57:54.590934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869df2353e62'
down_revision: Union[str, Sequence[str], None] = '48c7effbe24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_location', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_location_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_location', schema=None) as batch_op:
        batch_op.drop_constraint('uq_location_name', type_='unique')

    # ### end Alembic commands ###
