"""init

Revision ID: cc396ecd8cd9
Revises:
Create Date: 2026-04-27 13:05:00.181399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from application.core.config import settings

# revision identifiers, used by Alembic.
revision: str = 'cc396ecd8cd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f'CREATE SCHEMA IF NOT EXISTS {settings.POSTGRES_SCHEMA}')
    op.create_table(
        'auth_user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'password',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column(
            'username',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column(
            'last_name',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column(
            'email',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=True,
        ),
        sa.Column('is_staff', sa.Boolean(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('date_joined', sa.DateTime(), nullable=False),
        sa.Column(
            'first_name',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
        schema=settings.POSTGRES_SCHEMA,
    )
    op.create_table(
        'blog_category',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.Column(
            'title',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column(
            'description',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column(
            'slug',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug'),
        schema=settings.POSTGRES_SCHEMA,
    )
    op.create_table(
        'blog_location',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.Column(
            'name',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        schema=settings.POSTGRES_SCHEMA,
    )
    op.create_table(
        'blog_post',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.Column(
            'title',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column(
            'text',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('location_id', sa.Integer(), nullable=True),
        sa.Column(
            'image',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=True,
        ),
        sa.Column('pub_date', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'],
            [f'{settings.POSTGRES_SCHEMA}.auth_user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['category_id'],
            [f'{settings.POSTGRES_SCHEMA}.blog_category.id'],
        ),
        sa.ForeignKeyConstraint(
            ['location_id'],
            [f'{settings.POSTGRES_SCHEMA}.blog_location.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=settings.POSTGRES_SCHEMA,
    )
    op.create_table(
        'blog_comment',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column(
            'text',
            sa.String().with_variant(sa.String(length=255), 'postgresql'),
            nullable=False,
        ),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'],
            [f'{settings.POSTGRES_SCHEMA}.auth_user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['post_id'],
            [f'{settings.POSTGRES_SCHEMA}.blog_post.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=settings.POSTGRES_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_comment', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('blog_post', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('blog_location', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('blog_category', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('auth_user', schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###
